"""baseline schema

Revision ID: 70c5a19c093f
Revises: 
Create Date: 2026-09-04 16:47:50.309553
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '70c5a19c093f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'dead_letter')", name='ck_jobs_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_jobs_attempt_count_non_negative'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_jobs_max_attempts_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('ix_jobs_queued_at', 'jobs', ['queued_at'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('taxonomy_version_id', sa.UUID(), nullable=True),
    sa.Column('input_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('output_valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_versions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_runs_created_at', 'model_runs', ['created_at'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_review_id', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('reviewer_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_reply_text', sa.Text(), nullable=True),
    sa.Column('owner_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=16), server_default='en', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analysis_status IN ('pending', 'analyzed', 'failed', 'skipped')", name='ck_reviews_analysis_status'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_review_id')
    )
    op.create_index('ix_reviews_analysis_status', 'reviews', ['analysis_status'], unique=False)
    op.create_index('ix_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('ix_reviews_rating', 'reviews', ['rating'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviews_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reviews_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reviews_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cursor_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'failed', 'partial')", name='ck_sync_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_runs_started_at', 'sync_runs', ['started_at'], unique=False)
    op.create_table('taxonomy_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_model_run_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('candidate', 'active', 'archived', 'failed')", name='ck_taxonomy_versions_status'),
    sa.ForeignKeyConstraint(['generation_model_run_id'], ['model_runs.id'], use_alter=True),
    sa.ForeignKeyConstraint(['parent_version_id'], ['taxonomy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_number')
    )
    op.create_index('uq_taxonomy_versions_single_active', 'taxonomy_versions', ['status'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('evaluation_type', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('taxonomy_version_id', sa.UUID(), nullable=True),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluation_runs_created_at', 'evaluation_runs', ['created_at'], unique=False)
    op.create_table('review_analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('taxonomy_version_id', sa.UUID(), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('classifier_type', sa.String(length=16), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("classifier_type IN ('llm', 'ml', 'hybrid', 'manual')", name='ck_review_analyses_classifier_type'),
    sa.CheckConstraint('overall_confidence IS NULL OR (overall_confidence BETWEEN 0 AND 1)', name='ck_review_analyses_confidence_range'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_analyses_current', 'review_analyses', ['review_id'], unique=False, postgresql_where=sa.text('superseded_at IS NULL'))
    op.create_index('ix_review_analyses_review', 'review_analyses', ['review_id'], unique=False)
    op.create_index('ix_review_analyses_taxonomy_version', 'review_analyses', ['taxonomy_version_id'], unique=False)
    op.create_table('taxonomy_changes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('from_version_id', sa.UUID(), nullable=True),
    sa.Column('to_version_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('old_node_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('new_node_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("change_type IN ('add', 'rename', 'merge', 'split', 'move', 'delete', 'rollback')", name='ck_taxonomy_changes_change_type'),
    sa.ForeignKeyConstraint(['from_version_id'], ['taxonomy_versions.id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['taxonomy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_taxonomy_changes_to_version', 'taxonomy_changes', ['to_version_id'], unique=False)
    op.create_table('taxonomy_nodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('taxonomy_version_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('depth >= 0', name='ck_taxonomy_nodes_depth_non_negative'),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taxonomy_version_id', 'slug', name='uq_taxonomy_nodes_version_slug')
    )
    op.create_index('ix_taxonomy_nodes_version', 'taxonomy_nodes', ['taxonomy_version_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('taxonomy_node_id', sa.UUID(), nullable=False),
    sa.Column('taxonomy_version_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('candidate', 'accepted', 'dismissed', 'resolved')", name='ck_anomalies_status'),
    sa.CheckConstraint('period_start <= period_end', name='ck_anomalies_period_order'),
    sa.CheckConstraint('support_count >= 0', name='ck_anomalies_support_non_negative'),
    sa.ForeignKeyConstraint(['taxonomy_node_id'], ['taxonomy_nodes.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_node', 'anomalies', ['taxonomy_node_id'], unique=False)
    op.create_index('ix_anomalies_period', 'anomalies', ['period_start', 'period_end'], unique=False)
    op.create_table('review_aspects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_analysis_id', sa.UUID(), nullable=False),
    sa.Column('taxonomy_node_id', sa.UUID(), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_text', sa.Text(), server_default='', nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sentiment IN ('positive', 'neutral', 'negative')", name='ck_review_aspects_sentiment'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_review_aspects_confidence_range'),
    sa.ForeignKeyConstraint(['review_analysis_id'], ['review_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_node_id'], ['taxonomy_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_aspects_analysis', 'review_aspects', ['review_analysis_id'], unique=False)
    op.create_index('ix_review_aspects_node', 'review_aspects', ['taxonomy_node_id'], unique=False)
    op.create_index('ix_review_aspects_sentiment', 'review_aspects', ['sentiment'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('anomaly_id', sa.UUID(), nullable=True),
    sa.Column('taxonomy_node_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('evidence_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='new', nullable=False),
    sa.Column('generated_by_model_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manual_status_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'monitoring', 'resolved')", name='ck_insights_status'),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['generated_by_model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_node_id'], ['taxonomy_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insights_created_at', 'insights', ['created_at'], unique=False)
    op.create_index('ix_insights_status', 'insights', ['status'], unique=False)
    op.create_table('insight_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='planned', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'completed', 'cancelled')", name='ck_insight_actions_status'),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_actions_insight', 'insight_actions', ['insight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insight_actions_insight', table_name='insight_actions')
    op.drop_table('insight_actions')
    op.drop_index('ix_insights_status', table_name='insights')
    op.drop_index('ix_insights_created_at', table_name='insights')
    op.drop_table('insights')
    op.drop_index('ix_review_aspects_sentiment', table_name='review_aspects')
    op.drop_index('ix_review_aspects_node', table_name='review_aspects')
    op.drop_index('ix_review_aspects_analysis', table_name='review_aspects')
    op.drop_table('review_aspects')
    op.drop_index('ix_anomalies_period', table_name='anomalies')
    op.drop_index('ix_anomalies_node', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_taxonomy_nodes_version', table_name='taxonomy_nodes')
    op.drop_table('taxonomy_nodes')
    op.drop_index('ix_taxonomy_changes_to_version', table_name='taxonomy_changes')
    op.drop_table('taxonomy_changes')
    op.drop_index('ix_review_analyses_taxonomy_version', table_name='review_analyses')
    op.drop_index('ix_review_analyses_review', table_name='review_analyses')
    op.drop_index('ix_review_analyses_current', table_name='review_analyses', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_table('review_analyses')
    op.drop_index('ix_evaluation_runs_created_at', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('uq_taxonomy_versions_single_active', table_name='taxonomy_versions', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('taxonomy_versions')
    op.drop_index('ix_sync_runs_started_at', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_table('settings')
    op.drop_index('ix_reviews_rating', table_name='reviews')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_index('ix_reviews_analysis_status', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_model_runs_created_at', table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_queued_at', table_name='jobs')
    op.drop_index('ix_jobs_job_type', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
